search_box=r"""//input[@id='searchboxinput']"""
search_find=r"""//button[@id='searchbox-searchbutton']"""
save=r"""//div[@class="R8c4Qb fontBodySmall"][normalize-space()="Save"]"""
directions1=r"""//button[@id="hArJGc"]"""
directions=r"""//button[@data-value="Directions"]"""
find_position=r"""//input[@placeholder="Choose starting point, or click on the map..."]"""
details=r"""//button[text()='Send directions to your phone']"""
kms=r"""//div[@class="ivN21e tUEI8e fontBodyMedium"]"""
bus=r"""//div[contains(@class, "fontHeadlineSmall") and contains(@class, "delay")]"""
#r"""//div[@class="Fk3sm fontHeadlineSmall delay-light"]"""
train=r"""(//div[@class="Fk3sm fontHeadlineSmall"])[1]"""
train_name=r"""//span[@class="cukLmd"]"""
flight=r"""(//button[@role='radio'])[6]"""
find_flight=r"""//a[@class='LE0rHc fontTitleSmall XbJon']"""
fecth_flight=r"""//span[@class='uchGue']"""
